AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation template for TwiFBeddit backend

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: entrypoint.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Backend:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  BackendApi:
    Description: "API Gateway endpoint URL for Prod stage function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
